# Generated by Django 6.0.3 on 2026-06-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('SERVICE_PROVIDER', 'Service Provider'), ('ADMIN', 'Admin')], default='CUSTOMER', max_length=50),
        ),
    ]
