# Generated by Django 6.0.3 on 2026-06-12 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_district_division_customuser_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.division'),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='upazila',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.district'),
        ),
        migrations.AlterField(
            model_name='upazila',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
