# Generated by Django 6.0.3 on 2026-06-13 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_district_division_alter_district_name_and_more'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.district'),
        ),
        migrations.RemoveField(
            model_name='upazila',
            name='district',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.division'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='upazila',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.upazila'),
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='Division',
        ),
        migrations.DeleteModel(
            name='Upazila',
        ),
    ]
