# Generated by Django 6.0.3 on 2026-06-06 11:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='completed_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
