# Generated by Django 6.0.3 on 2026-06-21 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_service_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='contact_base_price',
        ),
    ]
